name: Example
on: [push]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:

    - id: files_get
      name: Get files changed
      # See: https://github.com/marketplace/actions/changed-files-exporter
      # This is generate a JSON list of changed files in `steps.files_get.outputs.files_created`
      uses: futuratrepadeira/changed-files@v3.1.0
      with:
        repo-token: ${{ github.token }}

    - id: files_detect
      name: Detect if foo-service was changed
      run: |
        directory_trigger="foo-service/"
        directory_was_changed='no'

        # detect
        readarray -t changed_files <<<"$(jq -r '.[]' <<<'${{ steps.files_get.outputs.files_created }}')"
        for changed_file in ${changed_files[@]}; do
          echo "Checking: ${changed_file}"
          if [[ $changed_file =~ $directory_trigger ]]
          then
            echo " - ${directory_trigger} was changed with that file."
            directory_was_changed='yes'
          else
            echo " - ${directory_trigger} was not changed with that file."
          fi
        done
        echo "::set-output name=directory_was_changed::${directory_was_changed}"

      # Run this step, only if the foo-service directory was changed in this PR.
    - name: foo-service only change
      if: steps.files_detect.outputs.directory_was_changed == 'yes'
      run: |
        echo "Hello. foo-service only logic."

      # Run this step, only if the foo-service directory was not changed in this PR.
    - name: non foo-service only change
      if: steps.files_detect.outputs.directory_was_changed != 'yes'
      run: |
        echo "Hello. non foo-service only logic."
